# ### workspace-ci
# #### source: workspace
name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  precommit:
    name: Pre-Commit
    permissions:
      contents: read
    uses: ./.github/workflows/⚡reusable-precommit.yaml
    secrets: inherit

  # ### dart-lib-analyze
  # #### source: dart-lib
  analyze:
    name: Static Analysis
    permissions:
      contents: read
    uses: ./.github/workflows/⚡reusable-analyze.yaml
    secrets: inherit

  # ### dart-lib-unit
  # #### source: dart-lib
  unit:
    name: Unit and C0 Tests
    permissions:
      contents: read
    uses: ./.github/workflows/⚡reusable-test.yaml
    secrets: inherit
    with:
      mode: unit

  # ### dart-lib-meta
  # #### source: dart-lib
  meta:
    name: TestHelper Meta Tests
    permissions:
      contents: read
    uses: ./.github/workflows/⚡reusable-test.yaml
    secrets: inherit
    with:
      mode: meta

  # ### dart-lib-deadcode
  # #### source: dart-lib
  deadcode:
    name: Dead Code
    permissions:
      contents: read
    uses: ./.github/workflows/⚡reusable-deadcode.yaml
    secrets: inherit

  # ### dart-lib-package-validate
  # #### source: dart-lib
  package-validate:
    name: Package Validation
    permissions:
      contents: read
    uses: ./.github/workflows/⚡reusable-package-validate.yaml
    secrets: inherit

  # ### dart-lib-nix-check
  # #### source: dart-lib
  nix-check:
    name: Nix Check
    permissions:
      contents: read
    uses: ./.github/workflows/⚡reusable-nix-check.yaml
    secrets: inherit
